name: Playwright tests

on:
  pull_request:
    branches: [ staging, main, master ]
    types:
      - opened
      - synchronize
    paths:
      - '.github/workflows/playwright.yml'
      - 'src/**'
      - 'tests/playwright/**'
      - 'package.json'
      
  schedule:
    - cron: '0 6 1,16 * *'

  workflow_dispatch:

jobs:
  # First job: discover all the *.spec.ts files and output a JSON matrix.
  discover-tests:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.discover.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Discover test files
        id: discover
        run: |
          # Find all *.spec.ts files and strip out the directory so that later
          # when running in tests/playwright, the path is relative.
          files=$(find -name '*.spec.ts' -exec basename {} \;)
          # Build a JSON array with an object for each test file.
          arr="["
          first=1
          for f in $files; do
            if [ $first -eq 1 ]; then
              first=0
            else
              arr+=","
            fi
            arr+="{\"testFile\":\"$f\"}"
          done
          arr+="]"
          echo "matrix=$arr" >> "$GITHUB_OUTPUT"
        working-directory: tests/playwright/site.integrations.tests
  
  # Second job: run tests in parallel – one per file – using the matrix.
  test:
    needs: discover-tests
    timeout-minutes: 15
    strategy:
      matrix: ${{ fromJson(needs.discover-tests.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Publish extension to dist folder
        run: |
          npm ci
          npm i grunt -g
          grunt playwright

      - name: Install test dependencies
        run: npm ci
        working-directory: tests/playwright

      - name: Install Playwright browser (chromium)
        run: npx playwright install --with-deps chromium
        working-directory: tests/playwright

      - name: Run Playwright test for file ${{ matrix.testFile }}
        run: npx playwright test ${{ matrix.testFile }}
        working-directory: tests/playwright

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ matrix.testFile }}
          path: tests/playwright/playwright-report/
          retention-days: 30

      # If the test step fails, create an issue using the same method as before.
      - name: Create issue if test fails
        if: failure()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: |
            Playwright test failed: ${{ matrix.testFile }}
          assignees: ${{ github.repository_owner }}
          labels: bug, failed-tests
          body: |
            ## Failure Report:
            
            > [!IMPORTANT]
            > Details on failed run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
            - **Test File:** `${{ matrix.testFile }}`
            - **Author:** trossr32
            - **Branch:** `${{ github.ref }}`
            - **Commit:** ${{ github.sha }}
            - **Workflow:** `${{ github.workflow_ref }}`
